#!/usr/bin/env python3
"""
Create a test video with Hindi audio using Google Text-to-Speech
"""

from gtts import gTTS
import subprocess
from pathlib import Path

# Hindi text (Devanagari script)
hindi_text = """
नमस्ते दोस्तों! मैं आपको एक रोचक कहानी सुनाने जा रहा हूं।
आज हम बात करेंगे तकनीक के बारे में।
आर्टिफिशियल इंटेलिजेंस आज के समय में बहुत महत्वपूर्ण है।
यह हमारे जीवन को आसान बना रहा है।
वीडियो एडिटिंग भी अब बहुत सरल हो गई है।
क्या आप जानते हैं कि सॉफ्टवेयर कैसे काम करता है?
यह बहुत दिलचस्प विषय है।
चलिए इसके बारे में और जानते हैं।
धन्यवाद!
"""

print("Creating Hindi audio using Google Text-to-Speech...")

# Generate Hindi audio
tts = gTTS(text=hindi_text, lang='hi', slow=False)
audio_output = Path("hindi_audio.mp3")
tts.save(str(audio_output))
print(f"✓ Hindi audio created: {audio_output}")

# Convert MP3 to WAV
wav_output = Path("hindi_audio.wav")
print(f"\nConverting MP3 to WAV...")
subprocess.run([
    'ffmpeg',
    '-i', str(audio_output),
    '-ar', '16000',
    '-ac', '1',
    '-y',
    str(wav_output)
], capture_output=True, check=True)
print(f"✓ WAV audio created: {wav_output}")

# Get audio duration
result = subprocess.run([
    'ffprobe',
    '-v', 'error',
    '-show_entries', 'format=duration',
    '-of', 'default=noprint_wrappers=1:nokey=1',
    str(wav_output)
], capture_output=True, text=True, check=True)
audio_duration = float(result.stdout.strip())
print(f"  Audio duration: {audio_duration:.2f}s")

# Create video with Hindi audio
# Loop the silent video to match audio duration
video_input = Path("test_input.mp4")
hindi_video_output = Path("hindi_test_video.mp4")

print(f"\nCreating Hindi video...")
subprocess.run([
    'ffmpeg',
    '-stream_loop', '-1',  # Loop video
    '-i', str(video_input),
    '-i', str(wav_output),
    '-c:v', 'libx264',
    '-preset', 'medium',
    '-crf', '23',
    '-c:a', 'aac',
    '-b:a', '128k',
    '-shortest',  # Stop when shortest input ends (the audio)
    '-y',
    str(hindi_video_output)
], capture_output=True, check=True)

print(f"✓ Hindi video created: {hindi_video_output}")

# Get video info
result = subprocess.run([
    'ffprobe',
    '-v', 'error',
    '-select_streams', 'v:0',
    '-show_entries', 'stream=width,height',
    '-of', 'json',
    str(hindi_video_output)
], capture_output=True, text=True, check=True)

import json
video_info = json.loads(result.stdout)
if video_info['streams']:
    stream = video_info['streams'][0]
    print(f"  Resolution: {stream['width']}x{stream['height']}")

print(f"  File size: {hindi_video_output.stat().st_size / 1024 / 1024:.2f} MB")

print("\n" + "="*60)
print("Hindi test video created successfully!")
print("="*60)
print(f"\nYou can now use '{hindi_video_output}' to test the full pipeline:")
print("  1. WhisperX transcription (Hindi → text with timestamps)")
print("  2. Hindi → Roman transliteration")
print("  3. Subtitle rendering with word-level timing")
print("  4. 9:16 vertical video with subtitles")
print("\nNote: The video contains Hindi speech generated by Google TTS")
print("      talking about AI, technology, and video editing.")
